version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - seaweedfs
    networks:
      - backend

  seaweedfs:
    build:
      context: ./
      dockerfile: Dockerfile.weed
    ports:
      - "8080:8080"
      - "9333:9333"
    networks:
      - backend

networks:
  backend: