FROM alpine

RUN wget https://github.com/chrislusf/seaweedfs/releases/download/2.38/linux_amd64.tar.gz \
    && tar -C . -xzf linux_amd64.tar.gz  \
    && mkdir -p weedvol

EXPOSE 8080 9333
ENTRYPOINT [ "./weed", "server", "-dir=./weedvol", "-s3"]
